on: [push]

jobs:
  build:
    
    runs-on: ubuntu-latest
    container: 'rocker/tidyverse:latest'

    steps:
      - uses: actions/checkout@v2
      - name: install icesSAG
        run: Rscript -e 'test.R'
